/*
# RunnerAI Core Schema

## Overview
Creates the full data model for RunnerAI, an AI running coach. All tables are
owner-scoped (per-user) with Row Level Security. Owner columns default to
auth.uid() so client inserts that omit user_id still satisfy RLS.

## New Tables
1. `profiles` - extended sports profile linked to auth.users (1:1)
2. `workouts` - imported/synced activities (km, pace, hr, cadence, etc.)
3. `training_plans` - AI-generated training plans
4. `plan_sessions` - individual sessions within a plan
5. `ai_messages` - conversation history with the AI coach
6. `achievements` - badges earned by the user
7. `notifications` - smart notifications generated by the AI
8. `user_stats` - latest computed metrics (fatigue, recovery, load, VO2)

## Security
- RLS enabled on every table.
- Each table has 4 owner-scoped policies (select/insert/update/delete).
- Owner column default is auth.uid() everywhere.

## Notes
1. All timestamps are timestamptz with now() default.
2. enums for experience_level and goal_type keep data clean.
3. jsonb columns store flexible AI/metric payloads without schema churn.
4. Indexes on user_id and created_at for common query patterns.
*/

-- Extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ===== ENUMS =====
DO $$ BEGIN
  CREATE TYPE experience_level AS ENUM ('beginner', 'intermediate', 'advanced', 'elite');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE goal_type AS ENUM ('5k','10k','half_marathon','marathon','ultramarathon','weight_loss','endurance');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE risk_level AS ENUM ('low','medium','high');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE plan_status AS ENUM ('active','completed','paused');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE session_status AS ENUM ('pending','completed','skipped','missed');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE notification_type AS ENUM ('recovery','workout','achievement','insight','plan');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ===== PROFILES =====
CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text NOT NULL,
  full_name text,
  avatar_url text,
  age int,
  sex text CHECK (sex IN ('male','female','other')),
  height_cm numeric,
  weight_kg numeric,
  country text,
  city text,
  experience experience_level DEFAULT 'beginner',
  weekly_km numeric DEFAULT 0,
  goal goal_type,
  is_premium boolean NOT NULL DEFAULT false,
  premium_since timestamptz,
  onboarded boolean NOT NULL DEFAULT false,
  total_xp int NOT NULL DEFAULT 0,
  level int NOT NULL DEFAULT 1,
  current_streak int NOT NULL DEFAULT 0,
  longest_streak int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "select_own_profile" ON profiles;
CREATE POLICY "select_own_profile" ON profiles FOR SELECT TO authenticated USING (auth.uid() = id);
DROP POLICY IF EXISTS "insert_own_profile" ON profiles;
CREATE POLICY "insert_own_profile" ON profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
DROP POLICY IF EXISTS "update_own_profile" ON profiles;
CREATE POLICY "update_own_profile" ON profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
DROP POLICY IF EXISTS "delete_own_profile" ON profiles;
CREATE POLICY "delete_own_profile" ON profiles FOR DELETE TO authenticated USING (auth.uid() = id);

-- ===== WORKOUTS =====
CREATE TABLE IF NOT EXISTS workouts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  source text, -- strava, garmin, apple_health, google_fit, coros, polar, manual
  external_id text,
  activity_type text NOT NULL DEFAULT 'run',
  title text,
  distance_km numeric NOT NULL DEFAULT 0,
  duration_sec int NOT NULL DEFAULT 0,
  avg_pace_sec_per_km int,
  avg_heart_rate int,
  max_heart_rate int,
  cadence int,
  elevation_gain_m int,
  calories int,
  avg_power int,
  effort int, -- RPE 1-10
  started_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE workouts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "select_own_workouts" ON workouts;
CREATE POLICY "select_own_workouts" ON workouts FOR SELECT TO authenticated USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "insert_own_workouts" ON workouts;
CREATE POLICY "insert_own_workouts" ON workouts FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "update_own_workouts" ON workouts;
CREATE POLICY "update_own_workouts" ON workouts FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "delete_own_workouts" ON workouts;
CREATE POLICY "delete_own_workouts" ON workouts FOR DELETE TO authenticated USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_workouts_user_started ON workouts(user_id, started_at DESC);

-- ===== TRAINING PLANS =====
CREATE TABLE IF NOT EXISTS training_plans (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  goal goal_type,
  target_race_date date,
  target_time_sec int,
  weeks int NOT NULL DEFAULT 12,
  status plan_status NOT NULL DEFAULT 'active',
  current_week int NOT NULL DEFAULT 1,
  generated_context jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE training_plans ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "select_own_plans" ON training_plans;
CREATE POLICY "select_own_plans" ON training_plans FOR SELECT TO authenticated USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "insert_own_plans" ON training_plans;
CREATE POLICY "insert_own_plans" ON training_plans FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "update_own_plans" ON training_plans;
CREATE POLICY "update_own_plans" ON training_plans FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "delete_own_plans" ON training_plans;
CREATE POLICY "delete_own_plans" ON training_plans FOR DELETE TO authenticated USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_plans_user ON training_plans(user_id, created_at DESC);

-- ===== PLAN SESSIONS =====
CREATE TABLE IF NOT EXISTS plan_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  plan_id uuid NOT NULL REFERENCES training_plans(id) ON DELETE CASCADE,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  week_number int NOT NULL,
  day_of_week int NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
  date date NOT NULL,
  session_type text NOT NULL, -- easy, long, tempo, intervals, recovery, rest, strength
  title text NOT NULL,
  description text,
  distance_km numeric,
  duration_min int,
  target_pace_sec_per_km int,
  intensity text, -- easy, moderate, hard, threshold, vo2max
  status session_status NOT NULL DEFAULT 'pending',
  completed_workout_id uuid REFERENCES workouts(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE plan_sessions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "select_own_sessions" ON plan_sessions;
CREATE POLICY "select_own_sessions" ON plan_sessions FOR SELECT TO authenticated USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "insert_own_sessions" ON plan_sessions;
CREATE POLICY "insert_own_sessions" ON plan_sessions FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "update_own_sessions" ON plan_sessions;
CREATE POLICY "update_own_sessions" ON plan_sessions FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "delete_own_sessions" ON plan_sessions;
CREATE POLICY "delete_own_sessions" ON plan_sessions FOR DELETE TO authenticated USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_sessions_plan_week ON plan_sessions(plan_id, week_number, day_of_week);
CREATE INDEX IF NOT EXISTS idx_sessions_user_date ON plan_sessions(user_id, date);

-- ===== AI MESSAGES =====
CREATE TABLE IF NOT EXISTS ai_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  role text NOT NULL CHECK (role IN ('user','assistant')),
  content text NOT NULL,
  context jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE ai_messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "select_own_messages" ON ai_messages;
CREATE POLICY "select_own_messages" ON ai_messages FOR SELECT TO authenticated USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "insert_own_messages" ON ai_messages;
CREATE POLICY "insert_own_messages" ON ai_messages FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "delete_own_messages" ON ai_messages;
CREATE POLICY "delete_own_messages" ON ai_messages FOR DELETE TO authenticated USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_messages_user ON ai_messages(user_id, created_at DESC);

-- ===== ACHIEVEMENTS =====
CREATE TABLE IF NOT EXISTS achievements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  badge_id text NOT NULL,
  title text NOT NULL,
  description text,
  icon text,
  xp_awarded int NOT NULL DEFAULT 0,
  earned_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE achievements ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "select_own_achievements" ON achievements;
CREATE POLICY "select_own_achievements" ON achievements FOR SELECT TO authenticated USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "insert_own_achievements" ON achievements;
CREATE POLICY "insert_own_achievements" ON achievements FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "delete_own_achievements" ON achievements;
CREATE POLICY "delete_own_achievements" ON achievements FOR DELETE TO authenticated USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_achievements_user ON achievements(user_id, earned_at DESC);

-- ===== NOTIFICATIONS =====
CREATE TABLE IF NOT EXISTS notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  type notification_type NOT NULL,
  title text NOT NULL,
  body text NOT NULL,
  read boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "select_own_notifications" ON notifications;
CREATE POLICY "select_own_notifications" ON notifications FOR SELECT TO authenticated USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "insert_own_notifications" ON notifications;
CREATE POLICY "insert_own_notifications" ON notifications FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "update_own_notifications" ON notifications;
CREATE POLICY "update_own_notifications" ON notifications FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "delete_own_notifications" ON notifications;
CREATE POLICY "delete_own_notifications" ON notifications FOR DELETE TO authenticated USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id, created_at DESC);

-- ===== USER STATS (latest computed snapshot) =====
CREATE TABLE IF NOT EXISTS user_stats (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  fitness int NOT NULL DEFAULT 0,       -- CTL (chronic training load)
  fatigue int NOT NULL DEFAULT 0,       -- ATL (acute training load)
  recovery int NOT NULL DEFAULT 50,     -- 0-100 form/readiness
  training_load int NOT NULL DEFAULT 0, -- 7-day km * intensity proxy
  vo2_max numeric NOT NULL DEFAULT 0,
  fatigue_score int NOT NULL DEFAULT 0, -- 0-100
  recovery_score int NOT NULL DEFAULT 50, -- 0-100
  injury_risk risk_level NOT NULL DEFAULT 'low',
  injury_risk_score int NOT NULL DEFAULT 0, -- 0-100
  total_distance_km numeric NOT NULL DEFAULT 0,
  total_workouts int NOT NULL DEFAULT 0,
  weekly_distance_km numeric NOT NULL DEFAULT 0,
  avg_pace_sec_per_km int,
  predicted_5k_sec int,
  predicted_10k_sec int,
  predicted_half_sec int,
  predicted_full_sec int,
  progress_pct numeric NOT NULL DEFAULT 0, -- improvement % vs 4 weeks ago
  computed_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE user_stats ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "select_own_stats" ON user_stats;
CREATE POLICY "select_own_stats" ON user_stats FOR SELECT TO authenticated USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "insert_own_stats" ON user_stats;
CREATE POLICY "insert_own_stats" ON user_stats FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "update_own_stats" ON user_stats;
CREATE POLICY "update_own_stats" ON user_stats FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "delete_own_stats" ON user_stats;
CREATE POLICY "delete_own_stats" ON user_stats FOR DELETE TO authenticated USING (auth.uid() = user_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_stats_user_unique ON user_stats(user_id);
